### ISSUE TITLE
MailosaurClient constructor: default baseUrl value overriden with null

### ISSUE THREAD

**Issue by Gnativ** [mailosaur/mailosaur-dotnet#10]
https://github.com/mailosaur/mailosaur-dotnet/blob/7ffcff7d20da5bdd0e9fab63115fecbd85ff4659/Mailosaur/MailosaurClient.cs#L26

#L26 should be replaced with the following: 
public MailosaurClient(string apiKey) : this(apiKey) {}

**Comment by hippyhorse** [comment]
Resolved via https://github.com/mailosaur/mailosaur-dotnet/commit/8153c5dcd856e9968287bc1a73f33061e164f8be
