### ISSUE TITLE
File type of Previews

### ISSUE THREAD

**Issue by RenderMichael** [mailosaur/mailosaur-dotnet#24]
I would like to use the new Previews functionality in the latest release, and I pieced together how to use it by looking at the tests in [the relevant commit](https://github.com/mailosaur/mailosaur-dotnet/commit/da3cdd98650b2000897cab1f5e54ffdfbd85d391?w=1).

However, the tests only check the bytes are not null, and I'm not sure how to work with it. What file extension does it correlate to?

Thanks!

**Comment by jm-mailosaur** [comment]
Hey @RenderMichael sorry about the ambiguity, they are `.png` files, more information on how to write to disk here: https://mailosaur.com/docs/email-previews
