### ISSUE TITLE
High Severity Vulnerable Nuget Package Newtonsoft.Json 9.0.1

### ISSUE THREAD

**Issue by nathom791** [mailosaur/mailosaur-dotnet#27]
Latest main uses Newtonsoft.Json 9.0.1 which is marked as having at least 1 High severity vulnerability: https://www.nuget.org/packages/Newtonsoft.Json/9.0.1

Latest stable version of Newtonsoft.Json is 13.0.3.

![2024-12-20_11h33_31](https://github.com/user-attachments/assets/1697359c-fae1-405b-99f8-3717ca3a30b8)

**Comment by jm-mailosaur** [comment]
Thanks for raising this @nathom791, this is now updated in version 8.10.0 of the Mailosaur .NET client
